### ISSUE TITLE
How to create a channel? 

### ISSUE THREAD

**Issue by askucher** [tarun1475/Bitcoin-Lightning-Nodejs#1]

**Comment by tarun1475** [comment]
var lightning = require("bitcoin-lightning-nodejs");
var request = { 
    node_pubkey: <bytes>, 
    node_pubkey_string: <string>, 
    local_funding_amount: <int64>, 
    push_sat: <int64>, 
    target_conf: <int32>, 
    sat_per_byte: <int64>, 
    private: <bool>, 
    min_htlc_msat: <int64>, 
    remote_csv_delay: <uint32>, 
    min_confs: <int32>, 
    spend_unconfirmed: <bool>, 
  } 
 var call = lightning.ln.openChannel(request)
call.on('data', function(response) {
    // A response was received from the server.
    console.log(response);
  });
 call.on('status', function(status) {
    // The current status of the stream.
  });
call.on('end', function() {
    // The server has closed the stream.
  });
{ 
    "chan_pending": <PendingUpdate>,
    "chan_open": <ChannelOpenUpdate>,
}
